# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      csharp-deps:
        patterns:
          - "*" # Matches all C# dependencies
  - package-ecosystem: "npm"
    directory: "/PTrampert.SpaHost/test-client/" # Location of package.json files
    schedule:
      interval: "daily"
    groups:
      npm-deps:
        patterns:
          - "*" # Matches all npm dependencies
  - package-ecosystem: "docker"
    directory: "/PTrampert.SpaHost/" # Location of Dockerfiles
    schedule:
      interval: "daily"
    groups:
      docker-deps-spahost:
        patterns:
          - "*" # Matches all Docker dependencies

  - package-ecosystem: "docker"
    directory: "/PTrampert.SpaHost.SampleApi/" # Location of Dockerfiles
    schedule:
      interval: "daily"
    groups:
      docker-deps-spahost-sampleapi:
        patterns:
          - "*" # Matches all Docker dependencies