name: Build and Test PR
on:
  push:
    branches:
      - main
jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      main_branch: 'refs/heads/main'
  build-image:
    uses: ./.github/workflows/build-image.yml
    needs: version
    secrets: 
      DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
    with:
      Version: ${{needs.version.outputs.version}}
      ReleaseStream: ${{needs.version.outputs.release_stream}}
  publish-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [version, build-image]
    steps:
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{needs.version.outputs.version}}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true